version: '3.9'
services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
  #   networks:
  #     - backend
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "ELASTIC_PASSWORD=testpassword"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"

  # data_import:
  #   # build: ./data_import
  #   image: data_import
  #   networks:
  #     - backend
  #   volumes:
  #     - ./data:/app/data
  #   depends_on:
  #     - elasticsearch

  api_server:
    image: api_server
    networks:
      - backend
    ports:
      - "5034:5034"


volumes:
  esdata:


networks:
  backend: