version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=testpassword"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  data_import:
    image: data_import
    volumes:
      - ./data:/app/data
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: none
  api_server:
    image: api_server
    ports:
      - "5034:5034"     
  web-server:
    image: web-server
    ports:
      - '3011:3011'
volumes:
  esdata: