version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    networks:
      - wcontextnet
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=testpassword"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  data_import:
    image: data_import
    networks:
      - wcontextnet
    volumes:
      - ./data:/app/data
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: none
  api_server:
    # image: ghcr.io/hamzabealta/word-search-api-server:latest
    image: api_server
    networks:
      - wcontextnet
    ports:
      - '5034:5034' 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 350M
        reservations:
          cpus: '0.1'
          memory: 100M 
  web-server:
    # image: ghcr.io/hamzabealta/word-search-web-server:latest
    image: web-server
    networks:
      - wcontextnet
    ports:
      - '80:80'  # Forward host port 80 to container port 3010
      - '443:443' # Forward host port 443 to container port 3011
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"  # Get sure that this folder exists
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 350M
        reservations:
          cpus: '0.1'
          memory: 100M

volumes:
  esdata:

networks:
  wcontextnet: